language: ruby
rvm:
  - 1.9.3
bundler_args: --without development

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace --quiet
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - CUCUMBER_FORMAT=progress bundle exec rake cucumber

before_script:
  - cp config/sensitive.travis.yml config/sensitive.yml
  - cp db/migrate/20121130000000_prepare_tables.rb.travis db/migrate/20121130000000_prepare_tables.rb
  - rm db/migrate/20121130120617_simplify_edits.rb
  - psql -c 'create database journals_test' -U postgres