language: ruby
rvm:
  - 1.9.3

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_script:
  - cp config/sensitive.travis.yml config/sensitive.yml
  - cp db/migrate/20121130000000_prepare_tables.rb.travis db/migrate/20121130000000_prepare_tables.rb
  - psql -c 'create database journals_test' -U postgres