
development:
  adapter: postgresql
  encoding: unicode
  database: journals_development
  pool: 5
  username: journals
  password: <%= Rails.configuration.sensitive['db_pass'] %>

test: &test
  adapter: postgresql
  encoding: unicode
  database: journals_test
  pool: 5
  username: journals
  password: <%= Rails.configuration.sensitive['db_pass'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: journals_production
  pool: 5
  username: journals
  password: <%= Rails.configuration.sensitive['db_pass'] %>

cucumber:
  <<: *test