# Application configuration settings
app_full_name: the Small School Journals
app_name: journals-demo

git_branch: master # The git branch to deploy from

host: journals.kairi.in
user: journals
repository: git@github.com:rahul-sekhar/journals.git
deploy_folder: journals-demo # If using capistrano, the app will be deployed to /home/[user]/[deploy_folder]

email_domain: kairi.in
email_address: contact@kairi.in
email_server: email-smtp.us-west-2.amazonaws.com
email_port: 587
email_authentication: login

shared_assets: [ public/uploads ]
s3_backups_bucket: journals-backups
aws_domain: s3-ap-southeast-1.amazonaws.com
num_local_backups: 5
