# Application configuration settings
app_full_name: the Inwoods Journals
app_name: inwoods

git_branch: inwoods

host: inwoodsjournals.org
email_domain: inwoodsjournals.org
email_address: admin@inwoodsjournals.org
email_server: email-smtp.us-west-2.amazonaws.com
email_port: 587
email_authentication: login

shared_assets: [ public/uploads, uploads ]
s3_backups_bucket: inwoods-backups
aws_domain: s3-ap-southeast-1.amazonaws.com
num_local_backups: 5
