# Application configuration settings
app_full_name: Inwoods Journals
app_name: inwoods

git_branch: inwoods

host: inwoodsjournals.org
email_domain: inwoodsjournals.org
email_address: admin@inwoodsjournals.org

shared_assets: [ public/uploads ]
s3_backups_bucket: inwoods-backups
aws_domain: s3-ap-southeast-1.amazonaws.com
num_local_backups: 5
